
#include "name_generator.h"
#include <sstream>

using namespace Urho3D;

const String DEFAULT_NAME_PREFIX = "AutoGeneratedName";
NameGenerator::NameCountMap NameGenerator::s_nameCount;

//---------------------------------------------------------------------
NameGenerator::NameGenerator(void)
{
}

//---------------------------------------------------------------------
NameGenerator::~NameGenerator(void)
{
}

//---------------------------------------------------------------------
String NameGenerator::Next()
{
    return Next(DEFAULT_NAME_PREFIX);
}

//---------------------------------------------------------------------
String NameGenerator::Next( const String & prefix )
{
    if (s_nameCount.count(prefix) == 0)
        s_nameCount[prefix] = 0;
    std::stringstream ss;
    size_t & qty = s_nameCount[prefix];
    ss << prefix.CString() << "_" << qty++;
    return ss.str().c_str();
}

//---------------------------------------------------------------------
size_t NameGenerator::Count()
{
    size_t count = Count(DEFAULT_NAME_PREFIX);
    return count;
}

//---------------------------------------------------------------------
size_t NameGenerator::Count( const String & prefix )
{
    size_t count = (s_nameCount.count(prefix) == 0) ?
                                    0 : s_nameCount[prefix];
    return count;
}




