name: 🌐 JavaScript Builds
on: [push, pull_request]

# Global Settings
env:
  # Only used for the cache key. Increment version to force clean build.
  GODOT_BASE_BRANCH: 3.5
  SCONSFLAGS: verbose=yes warnings=all werror=yes debug_symbols=no
  EM_VERSION: 3.1.14
  EM_CACHE_FOLDER: "emsdk-cache"

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-javascript
  cancel-in-progress: true

jobs:
  javascript-template:
    runs-on: "ubuntu-20.04"
    name: Template (target=release, tools=no)

    steps:
      - uses: actions/checkout@v3

      - name: Set up Emscripten latest
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - name: Verify Emscripten setup
        run: |
          emcc -v

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }}
          platform: javascript
          target: release
          tools: false

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
